src/link/urls.py
from django.urls import path
from .views import cut_link, all_link, redirect_old

app_name = 'link'

urlpatterns = [
    path('history', all_link, name='history'),
    path('', cut_link, name='cut'),
    path('redirect/<int:link_id>', redirect_old, name='redirect_old')
]

src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('link.urls'))
]

src/link/models.py
from django.db import models

# Create your models here.


class Links(models.Model):
    old_link = models.CharField(max_length=500)
    new_link = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

src/link/forms.py
from django import forms


class LinkForm(forms.Form):
    link = forms.URLField()
    link.widget.attrs.update({
        'class': 'form-control',

        'placeholder': "Please enter link"})

src/link/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import LinkForm
from .models import Links
from .utils import gen_link


# Create your views here.


def cut_link(request):
    form = LinkForm
    link = False
    if request.method == 'POST':
        if not Links.objects.filter(old_link=request.POST['link']):
            Links.objects.create(
                old_link=request.POST['link'],
                new_link=gen_link())
    if Links.objects.filter(old_link=request.POST.get('link', False)):
        link = Links.objects.get(old_link=request.POST.get('link', False))
    return render(request, 'index.html', context={'link': link, 'form': form})


def all_link(request):
    links = Links.objects.all().order_by('-id')
    return render(request, 'index.html', context={'links': links})


def redirect_old(request, link_id):
    old_url = Links.objects.get(id=link_id).old_link
    return HttpResponseRedirect(old_url)

src/link/templates/index.html
<!DOCTYPE html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</head>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'link:cut' %}">Linkshorter</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'link:history' %}">История <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>

</header>
<body>
    {% if links %}
        {% for link in links %}
        <div class="card" style="width: 18rem;   max-width: 500px; margin: auto;">
          <div class="card-body">
            <h5 class="card-title">Ссылка</h5>
            <p class="card-text">{{ link.old_link }}</p>
            <a href={% url 'link:redirect_old' link.id %} target="_blank" class="card-text">{{ link.new_link }}</a>
            <p class ="card-text">{{ link.created }}</p>
          </div>
        </div>
        <br>
        {% endfor %}
    {% endif %}
    {% if form %}
        <form action="{% url 'link:cut' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" placeholder="Search" class="btn btn-success">Сократить</button>

        </form>
        {% if link %}
        <br>
        <div class="card" style="width: 18rem;   max-width: 500px; margin: auto;">
          <div class="card-body">
            <h5 class="card-title">Ссылка</h5>
            <p class="card-text">{{ link.old_link }}</p>
            <a href={% url 'link:redirect_old' link.id %} target="_blank" class="card-text">{{ link.new_link }}</a>
          </div>
        </div>
        <br>
        {% endif %}
    {% endif %}

</body>
<footer>


</footer>